export default {    
    "_0": "0",
    "_1": "1",
    "_2": "2",
    "_3": "3",
    "_4": "4",
    "_5": "5",
    "_6": "6",
    "_7": "7",
    "_8": "8",
    "_9": "9",    
    "abort": "Abort",
    "back":"Back",
    "addUser":"Add User",
    "userDetails":"User Details",
    "aborting": "Aborting...",
    "_cancel": "Cancel",
    "cancel": "Cancel / Refresh",
    "clear": "Clear",
    "dealerUserID": "Dealer User ID",
    "debug": "Debug",
    "firmwaredownloading": "Firmware Downloading ...",
    "firmwareDownload": "Firmware Download",
    "loading": "Loading...",
    "logout": "Log Out",
    "home": "Home", 
    "NapcoAccessControlSystem":"Napco Access Control System",
    "ok": "Ok",
    "password": "Password",
    "pleaseWait": "Please Wait...",
    "radioSerialNo": "Radio Serial Number",
    "radioStatus": "Radio Status",
    "submit": "Submit",    

};